workflows:
  windows-publishing-yaml:
    name: Windows Release build
    instance_type: windows
    max_build_duration: 60
    environment:
      flutter: 3.7.6
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build Flutter macOS
        script: |
          flutter build windows --release
    artifacts:
      - build/windows/**/kemi_installer.*
  linux-publishing-yaml:
    name: Linux Release build
    instance_type: linux
    max_build_duration: 60
    environment:
      flutter: 3.7.6
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build Flutter macOS
        script: |
          flutter build linux --release
    artifacts:
      - build/linux/**/kemi_installer.*
  macOS-publishing-yaml:
    name: macOS Release build
    max_build_duration: 60
    environment:
      flutter: 3.7.6
      xcode: 14.3
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
                    flutter packages pub get
      - name: Flutter analyze
        script: |
                    flutter analyze
      - name: Install pods
        script: |
                    find . -name "Podfile" -execdir pod install \;
      - name: Build Flutter macOS
        script: |
          flutter config --enable-macos-desktop && \
          flutter build macos --release      
      - name: Package macOS application
        script: |
          set -x

          # Command to find the path to your generated app
          APP_NAME=$(find $(pwd) -name "*.app")
          cd $(dirname "$APP_NAME")
          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg

          # Create an unsigned package
          xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg         
    artifacts:
      - build/macos/**/*.pkg
